### ISSUE TITLE
DockerComposeRule doesn't work as @Rule

### ISSUE THREAD

**Issue by nickmelis** [palantir/docker-compose-rule#160]
I have my rule in a JUnit integration test set up as follows:
`@ClassRule
public static DockerComposeRule docker = DockerComposeRule.builder()
    .file("src/test/resources/docker-compose.yml")
    .saveLogsTo("build/dockerLogs/dockerComposeRuleTest")
    .pullOnStartup(true)
    .waitingForService("vp0", HealthChecks.toHaveAllPortsOpen())
    .build();`

As soon as I change @ClassRule with @Rule, the test breaks with an "InitializationError" message and no log whatsoever. 
Is that a limitation/intended behaviour? I'd really like to run the rule for every single method rather than at class level.

**Comment by joelea** [comment]
DCR is definitely intended to be usable with the `@Rule` annotation. I'd also expect there to be some clues in the initialization error. 

- Does your stacktrace from the exception have a cause?
- How are you running the tests? Gradle? Maven? IntelliJ? Eclipse?

Thanks
Joe

**Comment by nickmelis** [comment]
* No cause or anything meaningful whatsoever
* Running tests inside Eclipse

I can take a screenshot if that is of any help

**Comment by joelea** [comment]
A screenshot would be helpful, thanks!

**Comment by nickmelis** [comment]
Actually I finally managed to get a meaningful message from Eclipse saying:

`org.junit.internal.runners.rules.ValidationError: The @Rule 'docker' must not be static or it must be annotated with @ClassRule.
	at org.junit.internal.runners.rules.RuleMemberValidator$MemberMustBeNonStaticOrAlsoClassRule.validate(RuleMemberValidator.java:183)
	at org.junit.internal.runners.rules.RuleMemberValidator.validateMember(RuleMemberValidator.java:99)
	at org.junit.internal.runners.rules.RuleMemberValidator.validate(RuleMemberValidator.java:93)
	at org.junit.runners.BlockJUnit4ClassRunner.validateFields(BlockJUnit4ClassRunner.java:196)
	at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:129)
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

`
which is pretty self explanatory. We should be able to close this down unless anyone has any objections.

**Comment by joelea** [comment]
Thanks! Hope everything works out for you.
