### ISSUE TITLE
Docker's new version format breaks Docker.version()

### ISSUE THREAD

**Issue by samwright** [palantir/docker-compose-rule#173]
Tests that fail: 
- DockerComposeRuleNativeHealthcheckIntegrationTest 
- ContainerIntegrationTests

Stacktrace:
```
Numeric identifier MUST NOT contain leading zeroes
	at com.github.zafarkhaja.semver.VersionParser.checkForLeadingZeroes(VersionParser.java:479)
	at com.github.zafarkhaja.semver.VersionParser.numericIdentifier(VersionParser.java:407)
	at com.github.zafarkhaja.semver.VersionParser.parseVersionCore(VersionParser.java:287)
	at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:255)
	at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:195)
	at com.github.zafarkhaja.semver.Version.valueOf(Version.java:265)
	at com.palantir.docker.compose.execution.Docker.version(Docker.java:54)
	at com.palantir.docker.compose.connection.ContainerIntegrationTests.testStateChanges_withHealthCheck(ContainerIntegrationTests.java:59)
etc...
```
The tests run Docker.version() which tries to parse the docker version as a semantic version using the java-semver library, which considers that the latest docker version "17.03.0-ce" to be malformed because a numeric identifier (i.e. "03") contains a leading zero.

Docker's version format has recently been changed to `YY.MM` (see https://github.com/docker/docker/releases/tag/v17.03.0-ce) as part of a move making a release every two months. IMHO semantic versioning works so why change it, but I doubt we will be able to convince them otherwise. I haven't seen if docker-compose will also move to the `YY.MM` format.

I suggest we change Docker.version() and DockerCompose.version() to return a String instead of a java-semver Version, and remove the java-semver library (I don't see it being used elsewhere). Annoyingly we can't just do lexicographic comparison on the version string for comparing versions, since `17.03.3-ce < 17.03.11-ce`, and we need to make sure we can compare the old version formats with the new ones (e.g. in DefaultDockerCompose we check that the `version >= 1.7.0`). 

I can write a Comparator and some utility methods for comparing these versions, e.g. using `^(\d+)\.(\d+)\.(\d+)(?:-.*)?$` would capture ["1","7","0"] from "1.7.0" and ["17","03","0"] from "17.03.0-ce", then 
using `com.google.common.collect.Comparators.lexicographical(Comparator.naturalOrder())` would give the correct order.

Thoughts?

**Comment by samwright** [comment]
Simpler solution was to parse the version string as three ints to construct the semver Version from. See pull request #177
