### ISSUE TITLE
Why am I getting ExceptionInInitializerError

### ISSUE THREAD

**Issue by dnjiao** [palantir/docker-compose-rule#190]
I have a custom rule for my integration test which has the path to test yaml file hardcoded.
```
public class MTestRule<T> implements TestRule {
	private T service;
	public MTestRule(String service, Class<T>serviceKlass) {
		this("src/test/resources/test.yml", service, serviceKlass, null);
	}
        public MTestRule(String testFile, String serviceName, Class<T>serviceKlass, Properties config) {	
		// docker container internal port
		int port = 8080;
		try {
			port = Integer.parseInt(config.getProperty("port"));
		} catch (Exception e){};
		final int internalPort = port;
		
		final String urlPattern = "http://$HOST:$EXTERNAL_PORT";
				
		DockerComposeRule dockerRule = DockerComposeRule.builder()
				.file(testFile)
				.waitingForService(serviceName, HealthChecks.toRespondOverHttp(internalPort, (p) -> p.inFormat(urlPattern)))
				.build();
        ..................
}
```
When I run the integration test, I am getting `ExceptionInInitializerError`.  

Below is the stack trace:

```
java.lang.ExceptionInInitializerError: null
        at com.palantir.docker.compose.execution.DockerComposeExecutable.lambda$dockerComposePath$8(DockerComposeExecuta    ble.java:52)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.palantir.docker.compose.execution.DockerComposeExecutable.dockerComposePath(DockerComposeExecutable.java:    52)
        at com.palantir.docker.compose.execution.ImmutableDockerComposeExecutable.access$501(ImmutableDockerComposeExecu    table.java:22)
        at com.palantir.docker.compose.execution.ImmutableDockerComposeExecutable$InitShim.dockerComposePath(ImmutableDo    ckerComposeExecutable.java:93)
        at com.palantir.docker.compose.execution.ImmutableDockerComposeExecutable.<init>(ImmutableDockerComposeExecutabl    e.java:46)
        at com.palantir.docker.compose.execution.ImmutableDockerComposeExecutable.<init>(ImmutableDockerComposeExecutabl    e.java:22)
        at com.palantir.docker.compose.execution.ImmutableDockerComposeExecutable$Builder.build(ImmutableDockerComposeEx    ecutable.java:342)
        at com.palantir.docker.compose.DockerComposeRule.dockerComposeExecutable(DockerComposeRule.java:77)
        at com.palantir.docker.compose.ImmutableDockerComposeRule.access$1801(ImmutableDockerComposeRule.java:31)
        at com.palantir.docker.compose.ImmutableDockerComposeRule$InitShim.dockerComposeExecutable(ImmutableDockerCompos    eRule.java:186)
        at com.palantir.docker.compose.ImmutableDockerComposeRule.<init>(ImmutableDockerComposeRule.java:84)
        at com.palantir.docker.compose.ImmutableDockerComposeRule.<init>(ImmutableDockerComposeRule.java:31)
        at com.palantir.docker.compose.ImmutableDockerComposeRule$Builder.build(ImmutableDockerComposeRule.java:1161)
        at com.lgc.dist.core.msp.test.MTestRule.<init>(MTestRule.java:86)
        at com.lgc.dist.core.msp.test.MTestRule.<init>(MTestRule.java:57)
        at com.lgc.dist.core.msp.example.helloservice.HelloServiceIT.<clinit>(HelloServiceIT.java:15)
```

This error occurs at line 52 of `DockerComposeExecutable` where `orElseThrow` is at:
```
@Value.Derived
protected String dockerComposePath() {
    String pathToUse = DOCKER_COMPOSE_LOCATIONS.preferredLocation()
            .orElseThrow(() -> new IllegalStateException(
                    "Could not find docker-compose, looked in: " + DOCKER_COMPOSE_LOCATIONS));

    log.debug("Using docker-compose found at " + pathToUse);

    return pathToUse;
}
```

I've set the `DOCKER_COMPOSE_LOCATION` in my environment which points to where `docker-compose` is installed.

It seems like the error happens before the yaml file is executed by `docker-compose`. The error message may suggests it have to do with the path. However, if the path is not valid, it would throw `IllegalStateException` instead of `ExceptionInInitializerError`. 

Could be that the version is not compatible? I am using 0.28.1 for `docker-compose-rule`, 1.13.1 for `docker` and 1.11.1 for `docker-compose`.

**Comment by joelea** [comment]
Hey @dnjiao,

Could you post the code you're using to create the `DockerComposeRule`.

Thanks
Joe

**Comment by joelea** [comment]
Well that is strange. I'll try and have a better look at this later, but for now it might be worth upgrading to the latest version; the little chunk of code for finding the right docker-compose location underwent some significant work recently.

**Comment by dnjiao** [comment]
It turns out the path was not set correctly for docker-compse. I am using git bash terminal on a Windows machine. I can run `docker-machine` without `.exe`. And if I do `which docker-compse`, it would print out the path without `.exe`. But the actual executable is `docker-compose.exe`. After I corrected the path, it works now. However I still don't understand while it did not throw `IllegalStateException` if the path is wrong

**Comment by fryz** [comment]
Closing this out as it looks like it's resolved (barring the question of why the ISE, which, if it's still an issue we should open a new issue and debug).
